### ISSUE TITLE
Major Flickering

### ISSUE THREAD

**Issue by hallcristobal** [jaburns/NintendoSpy#30]
Hello, I just followed the tutorial for building your own input device using an arduino uno, however I am getting some major flickering in NintendoSpy, even with blink reduction turned on. Any ideas?

**Comment by abductedPlatypus** [comment]
I added some extra anti-flickering features, expect it tomorrow on my branch and as pull request.

**Comment by zfleeman** [comment]
Hi, abductedPlatypus. I am using your build with all of the blink reduction options enabled, and I'm still getting some pretty major flickering. This can be seen in the unlisted video below. I have the Windows task manager set to "Realtime" for the nintendospy process, and I have changed the power options to give the USB ports full power. How can I fix this issue? I'm a little lost.

https://www.youtube.com/watch?v=Q2bwUXmiDAM

**Comment by abductedPlatypus** [comment]
Hey! Thanks for posting. I do agree, those glitches a very annoying.

Due to limitations with the Arduino hardware it's impossible to stop all glitching unfortunately. (I didn't work on that at all, so you would have to get a reply from jaburns but I don't think there's anything to do about it). 

The measures I added try to mask the glitches by hiding short button presses. But since you said it only happens during dying/loading, it might be that your console sends some data over the wire, or has some power problems, due to high energy demands when loading which cause some glitches.

I don't have hardware to test this anymore unfortunately (it's been 2.5 years since I last contributed to this project). So I fear I cannot help you find the root cause of your issue. I hope someone else can have a look into this issue. I'd be happy to give some pointers if some findings are posted here.
