### ISSUE TITLE
Gamecube Gameboy Player does bizarre things

### ISSUE THREAD

**Issue by zoggins** [jaburns/NintendoSpy#42]
I am trying to debug why starting up the gameboy player disk makes Nintendospy completely spaz out (all buttons and sticks randomly jumping around), but I am not familiar enough with the code (yet) to sort it out.  Any ideas or at least tips for debugging the issue.

**Comment by jaburns** [comment]
My guess would be that the system is checking to see if you have GBA plugged in or just a regular controller. The NintendoSpy isn't smart enough to know what kind of data is being passed on the controller wire, since the Arduino isn't fast enough to make those kind of decisions. It just grabs data and assumes it's controller data. So any time non-controller data is sent along the wire, you'll see it as the inputs freaking out on the viewer. I know with the N64 it spazzes out when reading from the memory pak in a controller.
